### ISSUE TITLE
Testing on Raspberry PI 3 B+ 

### ISSUE THREAD

**Issue by fr-og** [UpDryTwist/coolledx-driver#83]
I am trying to get this to work on a Raspberry PI 3 B+ running DietPi with Python 3.11 talking to one of these
https://www.temu.com/goods.html?_bg_fs=1&goods_id=601099538343960&sku_id=17592308206019&no_cache_id=9p2lr
which is controlled by the CoolLED1248 app

Bleak is working and discovers it.

```
# test_bleak.py
import asyncio
from bleak import BleakScanner

async def test_bleak():
    print("Scanning for Bluetooth devices...")
    try:
        devices = await BleakScanner.discover(timeout=5)
        if devices:
            print("Devices found:")
            for device in devices:
                print(f"Name: {device.name}, Address: {device.address}")
        else:
            print("No Bluetooth devices found.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    asyncio.run(test_bleak())
```

> dietpi@DietPi:~$ python3 testbleak.py
> Scanning for Bluetooth devices...
> Devices found:
> Name: CoolLEDM, Address: FF:00:00:05:27:EA

But utils/scan.py doesn't

> dietpi@DietPi:~$ python3 coolledx-driver/utils/scan.py
> Scanning for 10.0 seconds (change duration with -t) . . .
> 
> dietpi@DietPi:~$

And if I try to send something using utils/tweak_sign.py with the MAC address that test_bleak.py discovered... 

> dietpi@DietPi:~$ python3 coolledx-driver/utils/tweak_sign.py -a FF:00:00:05:27:EA -t TESTMESSAGE
> /home/dietpi/.local/lib/python3.11/site-packages/coolledx/client.py:124: FutureWarning: BLEDevice.metadata is deprecated and will be removed in a future version of Bleak, use AdvertisementData instead
>   manufacturer_data = ble_device.metadata["manufacturer_data"]
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> INFO:coolledx.client:Disconnected from device: BleakClient, FF:00:00:05:27:EA
> Traceback (most recent call last):
>   File "/home/dietpi/.local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 214, in connect
>     reply = await self._bus.call(
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/dbus_fast/aio/message_bus.py", line 385, in call
>     await future
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/dietpi/coolledx-driver/utils/tweak_sign.py", line 94, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/home/dietpi/coolledx-driver/utils/tweak_sign.py", line 26, in main
>     async with Client(args.address) as client:
>   File "/home/dietpi/.local/lib/python3.11/site-packages/coolledx/client.py", line 83, in __aenter__
>     await self.connect()
>   File "/home/dietpi/.local/lib/python3.11/site-packages/coolledx/client.py", line 142, in connect
>     await bleak_client.connect()
>   File "/home/dietpi/.local/lib/python3.11/site-packages/bleak/__init__.py", line 615, in connect
>     return await self._backend.connect(**kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dietpi/.local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 151, in connect
>     async with async_timeout(timeout):
>   File "/usr/lib/python3.11/asyncio/timeouts.py", line 98, in __aexit__
>     raise TimeoutError
> TimeoutError
> dietpi@DietPi:~$

**Comment by fr-og** [comment]
So I changed line 19 of scan.py to 
`COOLLEDX_DEVICE_NAME = "CoolLEDM"`

dietpi@DietPi:~/coolledx-driver/utils$ python3 scan.py
Scanning for 10.0 seconds (change duration with -t) . . .


--------------------------------------------------------------------------------
Device: CoolLEDM (FF:00:00:05:27:EA), RSSI: -29
  Height: 16, Width: 96
dietpi@DietPi:~/coolledx-driver/utils$

**Comment by UpDryTwist** [comment]
@fr-og - Sorry, I haven't been near this project in a while.  I'm picking it back up now for a bit.  You have a different hardware than I do, so I'm not really sure.  I ordered one, as I'm curious, but it won't arrive for a couple weeks.

I've updated the code so that you should now be able to pass in (to tweak_sign.py) your device name (-d "CoolLEDM") without needing to tweak the code itself.  Maybe you could try running scan.py (which'll now also scan for CoolLEDM) with the -e argument (extended info), and maybe -a (to scan everything in the environment), and maybe --log DEBUG to get the full debug output, and see what that turns up?  (Running tweak_sign with --log DEBUG may also reveal more, or not.)

**Comment by fr-og** [comment]
Hey @UpDryTwist, that's good to hear. I've dusted off the panel.

`scan.py -e`
> dietpi@DietPi:~$ python3 coolledx-driver/utils/scan.py -e
> Scanning for 10.0 seconds (change duration with -t) . . .
> 
> 
> --------------------------------------------------------------------------------
> Device: CoolLEDM (FF:00:00:05:27:EA), RSSI: -42
>   Height: 16, Width: 96
> AdvertisementData(local_name='CoolLEDM', manufacturer_data={9174: b"\xff\x00\x00\x05'\xea\x10\x00`\x01\xff"}, service_uuids=['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000fff0-0000-1000-8000-00805f9b34fb'], tx_power=7, rssi=-42)
> [Service] 0000fff0-0000-1000-8000-00805f9b34fb (Handle: 12): Vendor specific
>   [Characteristic] 0000fff1-0000-1000-8000-00805f9b34fb (Handle: 13): Vendor specific (read,write-without-response,notify), Value: {value}
>     [Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 15): Client Characteristic Configuration, Value: bytearray(b'\x00\x00')
> [Service] 00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
>   [Characteristic] 00002a05-0000-1000-8000-00805f9b34fb (Handle: 9): Service Changed (indicate)
>     [Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 11): Client Characteristic Configuration, Value: bytearray(b'\x02\x00')
> dietpi@DietPi:~$

`scan.py -e --log DEBUG`
> dietpi@DietPi:~$ python3 coolledx-driver/utils/scan.py -e --log DEBUG
> Scanning for 10.0 seconds (change duration with -t) . . .
> 
> DEBUG:bleak.backends.bluezdbus.manager:initial properties: {'/org/bluez': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.AgentManager1': {}, 'org.bluez.ProfileManager1': {}, 'org.bluez.HealthManager1': {}}, '/org/bluez/test': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.SimAccessTest1': {}}, '/org/bluez/hci0': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Adapter1': {'Address': 'B8:27:EB:9D:C0:95', 'AddressType': 'public', 'Name': 'DietPi', 'Alias': 'DietPi', 'Class': 4194304, 'Powered': True, 'PowerState': 'on', 'Discoverable': False, 'DiscoverableTimeout': 180, 'Pairable': False, 'PairableTimeout': 0, 'Discovering': False, 'UUIDs': ['0000112d-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '00001844-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb'], 'Modalias': 'usb:v1D6Bp0246d0542', 'Roles': ['central', 'peripheral']}, 'org.freedesktop.DBus.Properties': {}, 'org.bluez.BatteryProviderManager1': {}, 'org.bluez.GattManager1': {}, 'org.bluez.AdvertisementMonitorManager1': {'SupportedMonitorTypes': ['or_patterns'], 'SupportedFeatures': []}, 'org.bluez.Media1': {'SupportedUUIDs': ['0000110a-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb']}, 'org.bluez.NetworkServer1': {}, 'org.bluez.SimAccess1': {'Connected': False}, 'org.bluez.LEAdvertisingManager1': {'ActiveInstances': 0, 'SupportedInstances': 5, 'SupportedIncludes': ['tx-power', 'appearance', 'local-name'], 'SupportedFeatures': [], 'SupportedCapabilities': {'MaxAdvLen': 31, 'MaxScnRspLen': 31}}}}
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0): ['org.bluez.Adapter1', {'Discovering': <dbus_fast.signature.Variant ('b', True)>}, []]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': <dbus_fast.signature.Variant ('s', FF:00:00:05:27:EA)>, 'AddressType': <dbus_fast.signature.Variant ('s', public)>, 'Name': <dbus_fast.signature.Variant ('s', CoolLEDM)>, 'Alias': <dbus_fast.signature.Variant ('s', CoolLEDM)>, 'Paired': <dbus_fast.signature.Variant ('b', False)>, 'Bonded': <dbus_fast.signature.Variant ('b', False)>, 'Trusted': <dbus_fast.signature.Variant ('b', False)>, 'Blocked': <dbus_fast.signature.Variant ('b', False)>, 'LegacyPairing': <dbus_fast.signature.Variant ('b', False)>, 'RSSI': <dbus_fast.signature.Variant ('n', -35)>, 'Connected': <dbus_fast.signature.Variant ('b', False)>, 'UUIDs': <dbus_fast.signature.Variant ('as', ['0000fff0-0000-1000-8000-00805f9b34fb'])>, 'Adapter': <dbus_fast.signature.Variant ('o', /org/bluez/hci0)>, 'ManufacturerData': <dbus_fast.signature.Variant ('a{qv}', {9174: <dbus_fast.signature.Variant ('ay', bytearray(b"\xff\x00\x00\x05\'\xea\x10\x00`\x01\xff"))>})>, 'TxPower': <dbus_fast.signature.Variant ('n', 7)>, 'ServicesResolved': <dbus_fast.signature.Variant ('b', False)>, 'AdvertisingFlags': <dbus_fast.signature.Variant ('ay', bytearray(b'\x06'))>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:__main__:Device detected: FF:00:00:05:27:EA: CoolLEDM AdvertisementData(local_name='CoolLEDM', manufacturer_data={9174: b"\xff\x00\x00\x05'\xea\x10\x00`\x01\xff"}, service_uuids=['0000fff0-0000-1000-8000-00805f9b34fb'], tx_power=7, rssi=-35)
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_04_B9_E3_4E_19_7B', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': <dbus_fast.signature.Variant ('s', 04:B9:E3:4E:19:7B)>, 'AddressType': <dbus_fast.signature.Variant ('s', public)>, 'Alias': <dbus_fast.signature.Variant ('s', 04-B9-E3-4E-19-7B)>, 'Paired': <dbus_fast.signature.Variant ('b', False)>, 'Bonded': <dbus_fast.signature.Variant ('b', False)>, 'Trusted': <dbus_fast.signature.Variant ('b', False)>, 'Blocked': <dbus_fast.signature.Variant ('b', False)>, 'LegacyPairing': <dbus_fast.signature.Variant ('b', False)>, 'RSSI': <dbus_fast.signature.Variant ('n', -83)>, 'Connected': <dbus_fast.signature.Variant ('b', False)>, 'UUIDs': <dbus_fast.signature.Variant ('as', [])>, 'Adapter': <dbus_fast.signature.Variant ('o', /org/bluez/hci0)>, 'ManufacturerData': <dbus_fast.signature.Variant ('a{qv}', {117: <dbus_fast.signature.Variant ('ay', bytearray(b'B\x04\x01\x80f\x04\xb9\xe3N\x19{\x06\xb9\xe3N\x19z\x01\xcb\xe8\xf8\x00\x00\x00'))>})>, 'ServicesResolved': <dbus_fast.signature.Variant ('b', False)>, 'AdvertisingFlags': <dbus_fast.signature.Variant ('ay', bytearray(b'\x00'))>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:__main__:Device detected: 04:B9:E3:4E:19:7B: 04-B9-E3-4E-19-7B AdvertisementData(manufacturer_data={117: b'B\x04\x01\x80f\x04\xb9\xe3N\x19{\x06\xb9\xe3N\x19z\x01\xcb\xe8\xf8\x00\x00\x00'}, rssi=-83)
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_88_C6_26_F3_32_3A', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': <dbus_fast.signature.Variant ('s', 88:C6:26:F3:32:3A)>, 'AddressType': <dbus_fast.signature.Variant ('s', public)>, 'Alias': <dbus_fast.signature.Variant ('s', 88-C6-26-F3-32-3A)>, 'Paired': <dbus_fast.signature.Variant ('b', False)>, 'Bonded': <dbus_fast.signature.Variant ('b', False)>, 'Trusted': <dbus_fast.signature.Variant ('b', False)>, 'Blocked': <dbus_fast.signature.Variant ('b', False)>, 'LegacyPairing': <dbus_fast.signature.Variant ('b', False)>, 'RSSI': <dbus_fast.signature.Variant ('n', -87)>, 'Connected': <dbus_fast.signature.Variant ('b', False)>, 'UUIDs': <dbus_fast.signature.Variant ('as', ['0000fe61-0000-1000-8000-00805f9b34fb'])>, 'Adapter': <dbus_fast.signature.Variant ('o', /org/bluez/hci0)>, 'ManufacturerData': <dbus_fast.signature.Variant ('a{qv}', {3: <dbus_fast.signature.Variant ('ay', bytearray(b'\x00\x91 \x00\x00\t\xc4]\x83\xfc\x98*\x88\xc6&\xf32:\x12'))>})>, 'ServicesResolved': <dbus_fast.signature.Variant ('b', False)>, 'AdvertisingFlags': <dbus_fast.signature.Variant ('ay', bytearray(b'\x06'))>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:__main__:Device detected: 88:C6:26:F3:32:3A: 88-C6-26-F3-32-3A AdvertisementData(manufacturer_data={3: b'\x00\x91 \x00\x00\t\xc4]\x83\xfc\x98*\x88\xc6&\xf32:\x12'}, service_uuids=['0000fe61-0000-1000-8000-00805f9b34fb'], rssi=-87)
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_04_B9_E3_4E_19_7B): ['org.bluez.Device1', {}, ['RSSI']]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_04_B9_E3_4E_19_7B', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_88_C6_26_F3_32_3A): ['org.bluez.Device1', {}, ['RSSI']]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA): ['org.bluez.Device1', {}, ['TxPower', 'RSSI']]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0): ['org.bluez.Adapter1', {'Discovering': <dbus_fast.signature.Variant ('b', False)>}, []]
> 
> --------------------------------------------------------------------------------
> Device: CoolLEDM (FF:00:00:05:27:EA), RSSI: -35
>   Height: 16, Width: 96
> AdvertisementData(local_name='CoolLEDM', manufacturer_data={9174: b"\xff\x00\x00\x05'\xea\x10\x00`\x01\xff"}, service_uuids=['0000fff0-0000-1000-8000-00805f9b34fb'], tx_power=7, rssi=-35)
> DEBUG:bleak.backends.bluezdbus.client:Connecting to device @ FF:00:00:05:27:EA
> DEBUG:bleak.backends.bluezdbus.client:Connecting to BlueZ path /org/bluez/hci0/dev_FF_00_00_05_27_EA
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA): ['org.bluez.Device1', {'Connected': <dbus_fast.signature.Variant ('b', True)>}, []]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.GattService1': {'UUID': <dbus_fast.signature.Variant ('s', 00001801-0000-1000-8000-00805f9b34fb)>, 'Device': <dbus_fast.signature.Variant ('o', /org/bluez/hci0/dev_FF_00_00_05_27_EA)>, 'Primary': <dbus_fast.signature.Variant ('b', True)>, 'Includes': <dbus_fast.signature.Variant ('ao', [])>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008/char0009', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.GattCharacteristic1': {'UUID': <dbus_fast.signature.Variant ('s', 00002a05-0000-1000-8000-00805f9b34fb)>, 'Service': <dbus_fast.signature.Variant ('o', /org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008)>, 'Value': <dbus_fast.signature.Variant ('ay', bytearray(b''))>, 'Notifying': <dbus_fast.signature.Variant ('b', False)>, 'Flags': <dbus_fast.signature.Variant ('as', ['indicate'])>, 'MTU': <dbus_fast.signature.Variant ('q', 247)>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008/char0009/desc000b', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.GattDescriptor1': {'UUID': <dbus_fast.signature.Variant ('s', 00002902-0000-1000-8000-00805f9b34fb)>, 'Characteristic': <dbus_fast.signature.Variant ('o', /org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008/char0009)>, 'Value': <dbus_fast.signature.Variant ('ay', bytearray(b''))>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.GattService1': {'UUID': <dbus_fast.signature.Variant ('s', 0000fff0-0000-1000-8000-00805f9b34fb)>, 'Device': <dbus_fast.signature.Variant ('o', /org/bluez/hci0/dev_FF_00_00_05_27_EA)>, 'Primary': <dbus_fast.signature.Variant ('b', True)>, 'Includes': <dbus_fast.signature.Variant ('ao', [])>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.GattCharacteristic1': {'UUID': <dbus_fast.signature.Variant ('s', 0000fff1-0000-1000-8000-00805f9b34fb)>, 'Service': <dbus_fast.signature.Variant ('o', /org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c)>, 'Value': <dbus_fast.signature.Variant ('ay', bytearray(b''))>, 'Notifying': <dbus_fast.signature.Variant ('b', False)>, 'Flags': <dbus_fast.signature.Variant ('as', ['read', 'write-without-response', 'notify'])>, 'WriteAcquired': <dbus_fast.signature.Variant ('b', False)>, 'NotifyAcquired': <dbus_fast.signature.Variant ('b', False)>, 'MTU': <dbus_fast.signature.Variant ('q', 247)>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesAdded (/): ['/org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d/desc000f', {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.GattDescriptor1': {'UUID': <dbus_fast.signature.Variant ('s', 00002902-0000-1000-8000-00805f9b34fb)>, 'Characteristic': <dbus_fast.signature.Variant ('o', /org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d)>, 'Value': <dbus_fast.signature.Variant ('ay', bytearray(b''))>}, 'org.freedesktop.DBus.Properties': {}}]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA): ['org.bluez.Device1', {'UUIDs': <dbus_fast.signature.Variant ('as', ['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000fff0-0000-1000-8000-00805f9b34fb'])>, 'ServicesResolved': <dbus_fast.signature.Variant ('b', True)>}, []]
> [Service] 0000fff0-0000-1000-8000-00805f9b34fb (Handle: 12): Vendor specific
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d): ['org.bluez.GattCharacteristic1', {'Value': <dbus_fast.signature.Variant ('ay', bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))>}, []]
> DEBUG:bleak.backends.bluezdbus.client:Read Characteristic 0000fff1-0000-1000-8000-00805f9b34fb | /org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
>   [Characteristic] 0000fff1-0000-1000-8000-00805f9b34fb (Handle: 13): Vendor specific (read,write-without-response,notify), Value: {value}
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d/desc000f): ['org.bluez.GattDescriptor1', {'Value': <dbus_fast.signature.Variant ('ay', bytearray(b'\x00\x00'))>}, []]
> DEBUG:bleak.backends.bluezdbus.client:Read Descriptor 15 | /org/bluez/hci0/dev_FF_00_00_05_27_EA/service000c/char000d/desc000f: bytearray(b'\x00\x00')
>     [Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 15): Client Characteristic Configuration, Value: bytearray(b'\x00\x00')
> [Service] 00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
>   [Characteristic] 00002a05-0000-1000-8000-00805f9b34fb (Handle: 9): Service Changed (indicate)
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008/char0009/desc000b): ['org.bluez.GattDescriptor1', {'Value': <dbus_fast.signature.Variant ('ay', bytearray(b'\x02\x00'))>}, []]
> DEBUG:bleak.backends.bluezdbus.client:Read Descriptor 11 | /org/bluez/hci0/dev_FF_00_00_05_27_EA/service0008/char0009/desc000b: bytearray(b'\x02\x00')
>     [Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 11): Client Characteristic Configuration, Value: bytearray(b'\x02\x00')
> DEBUG:bleak.backends.bluezdbus.client:Disconnecting ({/org/bluez/hci0/dev_FF_00_00_05_27_EA})
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA): ['org.bluez.Device1', {'ServicesResolved': <dbus_fast.signature.Variant ('b', False)>}, []]
> DEBUG:bleak.backends.bluezdbus.manager:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_FF_00_00_05_27_EA): ['org.bluez.Device1', {'Connected': <dbus_fast.signature.Variant ('b', False)>}, []]
> DEBUG:bleak.backends.bluezdbus.client:Device disconnected (/org/bluez/hci0/dev_FF_00_00_05_27_EA)
> DEBUG:bleak.backends.bluezdbus.client:_cleanup_all(/org/bluez/hci0/dev_FF_00_00_05_27_EA)
> dietpi@DietPi:~$

**Comment by UpDryTwist** [comment]
@fr-og , so:  I got a CoolLEDM sign, and the bad news is that it uses an entirely different command set, which isn't documented anywhere (anywhere that I could find, at any rate).  

1. Your errors don't look like sign protocol errors, though.  You should be able to connect to the sign just fine (I've finally run mine on a Raspberry as well, no issues connecting with either the CoolLEDX or the CoolLEDM) - the errors show up once you start trying to do something.  I'd poke around to ensure that you have decent permissions, etc.  If you're adventurous, you could build the container and just use the container (I have on my to-do to publish it to a public repo), which should solve much.
2. Also, be sure that you don't have a password set on the sign.  It looks like the CoolLEDM supports authentication - which I didn't implement.  That might or might not cause a problem.

I'll probably poke at trying to crack the protocol, but it looks like a ton of guesswork, so it'll have to fit in when I don't have something else to be solving.  If you're enthusiastic, I bundled some utilities for analyzing the traffic.

It would be good to figure this out, as it looks like they're beginning to shift to CoolLEDM . . .
